name: Semantic release 

on:
  push:
    branches:
      - dev
jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: install dependencies
        run: npm ci
      - name: listing dependencies
        run: npm list
      - name: build app
        run: npm run build
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}